-- 0000_initial_schemas.sql
CREATE SCHEMA IF NOT EXISTS zeiss;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS integration;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS app_suite;
